// Code generated by protoc-gen-nidhi. DO NOT EDIT.
// source: example/example.proto

package fuzz

import (
	fuzz "github.com/google/gofuzz"
	pb "github.com/srikrsna/kavach/example"
)

func FuzzExample(msg *pb.Example, c fuzz.Continue) {
    c.Fuzz(&msg.Name)
}

func FuzzListExamplesRequest(msg *pb.ListExamplesRequest, c fuzz.Continue) {
    c.Fuzz(&msg.Parent)
    c.Fuzz(&msg.PageSize)
    c.Fuzz(&msg.PageToken)
}

func FuzzListExamplesResponse(msg *pb.ListExamplesResponse, c fuzz.Continue) {
    c.Fuzz(&msg.Examples)
    c.Fuzz(&msg.NextPageToken)
}

func FuzzGetExampleRequest(msg *pb.GetExampleRequest, c fuzz.Continue) {
    c.Fuzz(&msg.Name)
}

func FuzzCreateExampleRequest(msg *pb.CreateExampleRequest, c fuzz.Continue) {
    c.Fuzz(&msg.Parent)
    c.Fuzz(&msg.ExampleId)
    c.Fuzz(&msg.Example)
}

func FuzzUpdateExampleRequest(msg *pb.UpdateExampleRequest, c fuzz.Continue) {
    c.Fuzz(&msg.Example)
    c.Fuzz(&msg.UpdateMask)
}

func FuzzDeleteExampleRequest(msg *pb.DeleteExampleRequest, c fuzz.Continue) {
    c.Fuzz(&msg.Name)
}
