// Code generated by protoc-gen-nidhi. DO NOT EDIT.
// source: vanguard/vanguard.proto

package fuzz

import (
	fuzz "github.com/google/gofuzz"
	pb "github.com/srikrsna/vanguard/vanguard"
)

func FuzzPermission(msg *pb.Permission, c fuzz.Continue) {
    c.Fuzz(&msg.Level)
    c.Fuzz(&msg.Resources)
}
