// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: kavach/kavach.proto

package kavachpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level     int64    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Resources []string `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *Permission) Reset() {
	*x = Permission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kavach_kavach_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_kavach_kavach_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_kavach_kavach_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Permission) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

var file_kavach_kavach_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         2862693,
		Name:          "kavach.assert",
		Tag:           "bytes,2862693,opt,name=assert",
		Filename:      "kavach/kavach.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string assert = 2862693;
	E_Assert = &file_kavach_kavach_proto_extTypes[0]
)

var File_kavach_kavach_proto protoreflect.FileDescriptor

var file_kavach_kavach_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x61, 0x76, 0x61, 0x63, 0x68, 0x2f, 0x6b, 0x61, 0x76, 0x61, 0x63, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x61, 0x76, 0x61, 0x63, 0x68, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x40, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x3a, 0x39, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74, 0x12, 0x1e, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe5, 0xdc, 0xae, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x72, 0x69, 0x6b, 0x72,
	0x73, 0x6e, 0x61, 0x2f, 0x6b, 0x61, 0x76, 0x61, 0x63, 0x68, 0x2f, 0x6b, 0x61, 0x76, 0x61, 0x63,
	0x68, 0x3b, 0x6b, 0x61, 0x76, 0x61, 0x63, 0x68, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_kavach_kavach_proto_rawDescOnce sync.Once
	file_kavach_kavach_proto_rawDescData = file_kavach_kavach_proto_rawDesc
)

func file_kavach_kavach_proto_rawDescGZIP() []byte {
	file_kavach_kavach_proto_rawDescOnce.Do(func() {
		file_kavach_kavach_proto_rawDescData = protoimpl.X.CompressGZIP(file_kavach_kavach_proto_rawDescData)
	})
	return file_kavach_kavach_proto_rawDescData
}

var file_kavach_kavach_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kavach_kavach_proto_goTypes = []interface{}{
	(*Permission)(nil),                 // 0: kavach.Permission
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_kavach_kavach_proto_depIdxs = []int32{
	1, // 0: kavach.assert:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kavach_kavach_proto_init() }
func file_kavach_kavach_proto_init() {
	if File_kavach_kavach_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kavach_kavach_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kavach_kavach_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kavach_kavach_proto_goTypes,
		DependencyIndexes: file_kavach_kavach_proto_depIdxs,
		MessageInfos:      file_kavach_kavach_proto_msgTypes,
		ExtensionInfos:    file_kavach_kavach_proto_extTypes,
	}.Build()
	File_kavach_kavach_proto = out.File
	file_kavach_kavach_proto_rawDesc = nil
	file_kavach_kavach_proto_goTypes = nil
	file_kavach_kavach_proto_depIdxs = nil
}
